[project]
name = "pathway-hackathon-2025"
version = "0.1.0"
description = ""
authors = [
    {name = "DhruvPokhriyal",email = "171908255+DhruvPokhriyal@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pathway (>=0.26.1,<0.27.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
